#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_unbound="0.0.1"
  jq -n --arg unbound "$ver_unbound" '{unbound: $unbound}'
}

version "$@"
